---
title: "SUN"
author: "Yueran SUN"
format: html
---

## Setup


```{r}

here::i_am("grades-lab.Rproj")
library(here)
library(tidyverse)
library(ggplot2)

```


## Question 1

```{r}

courses <- read_csv(here("data","courses.csv"))

```

## Question 2


```{r}

sorted_courses <- courses[order(courses$course), ]

column_names_english <- c("Course Name", "Identifier", "Module", "Number of Exams")

knitr::kable(
  sorted_courses, 
  col.names = column_names_english, 
  caption = "Course List"
)

```

## Question 3

```{r}

students <- read_csv(here("data", "students.csv"),
                     col_types = cols(
                       birth_date = col_date(),
                       sex = col_factor()
                     )
)

```


## Question 4

```{r}

grades <- read_delim(here("data", "grades.csv"), 
                     delim = ";",
                     na = "$")

```

## Question 5

```{r}

students |> ggplot()+geom_bar(aes(x = group))

```

## Question 6 

```{r}

ggplot(students, aes(x = group, fill = sex)) + geom_bar(position = "fill") +
    labs(
    x = "Student Group",
    y = "Number of Students",
    fill = "Gender"
  )

```

## Question 7

```{r}

library(lubridate)

students|>
  mutate(age = time_length(today() - birth_date, unit="year"))|>
  mutate(age = round(age)) -> students

students |> ggplot()+geom_bar(aes(x = age))



```

